#!/bin/bash
#################################################################
# A shell script to copy the DAQ time difference log files
#
# Nuruzzaman <nur@fnal.gov>, Date Created: 01/21/2017
#################################################################
LAST_MODIFIED="01/21/2017"

# Need to kerberize first. 
#source "/home/minos/minos_minerva_daq_time_difference/Kerberize"
kinit -k

#SOURCE_DIR=`pwd`
SOURCE_DIR="/home/minos/minos_minerva_daq_time_difference"
LOGS_DIR="$SOURCE_DIR/logs"
DAILY_TIME_LOGS="$LOGS_DIR/$(date +%Y%m%d)_minerva_minos_daq_time_difference.txt"

COPY_DIR="minerva@minerva-cr-03.fnal.gov:/home/minerva/cmtuser/Minerva_v10r9p1/Tools/ControlRoomTools/minos_minerva_daq_time_difference/logs"

COPY_LOG_FILE="$(scp -r ${DAILY_TIME_LOGS} ${COPY_DIR})"

echo -e "All files are copied\n"

